### ISSUE TITLE
Installation fails due to missing `R/mlr_graphs.R` in the mlr3pipelines CRAN release

### ISSUE THREAD

**Issue by wzel** [mlr-org/mlr3ordinal#11]
`R/mlr_graphs.R` exists in mlr3pipelines github repo, but for some reason is absent from the CRAN release, although it has been been added to the repo two months prior to the release. Unfortunately, there is no release branch, nor a release tag in the mlr3pipelines that would allow to investigate whether the missing file was intended to be included in the release or postponed to some future release. In the latter case, mlr3ordinal should require a > 0.1.3 version of mlr3pipelines. I submitted two github issues to mlr3pipelines to clarify the matter.

```
* installing *source* package ‘mlr3ordinal’ ...
** using staged installation
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘mlr3ordinal’:
 .onLoad failed in loadNamespace() for 'mlr3ordinal', details:
  call: get(x, envir = ns, inherits = FALSE)
  error: object 'mlr_graphs' not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/gnu/store/j5a6y65pzymmrvnkrx6qrzi2idg463wv-r-mlr3ordinal-0.1.0-9000-0.71b5029/site-library/mlr3ordinal’
```

**Comment by pat-s** [comment]
Thanks for mentioning!

I am actually not responsible for both packages but will clean up the situation.
